title: Default page template
pages: false
files: true
icon: asterisk

fields:
  # translations: translations
  title: title
  headline: headline
  heroImg:
    extends: hero
    width: 1
  text: defaultText

  ctaLine: ctaLine
  ctaHelp: ctaHelp
  cta: cta
  ctaText: ctaText
  ctaButton: ctaButton
  ctaLink: ctaLink
